#!/usr/bin/env python3
"""
Step 6 — IFC → CIM ABox Batch Instance Conversion
===================================================

M2 Milestone Critical Deliverable.

Reads ifc_to_cim_mapping.json (838 mapped instances from NBU_MedicalClinic IFC
files) and generates CIM v4.0 Turtle ABox triples for all equipment, space, and
floor instances.

Input : validation/ifc_to_cim_mapping.json
Output: project_deliverables/version02/cim/abox/nbu_medical_clinic_instances.ttl
Report: data_quality/abox_generation_report.md

Usage:
    python validation/step6_ifc_to_cim_abox.py
"""

from __future__ import annotations

import json
import re
import sys
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path

# ── Paths ────────────────────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
VALIDATION = ROOT / "validation"
CIM_ONTOLOGY = ROOT / "project_deliverables" / "version02" / "cim" / "ontology"
ABOX_DIR = ROOT / "project_deliverables" / "version02" / "cim" / "abox"
DATA_QUALITY = ROOT / "data_quality"

MAPPING_FILE = VALIDATION / "ifc_to_cim_mapping.json"
OUTPUT_TTL = ABOX_DIR / "nbu_medical_clinic_instances.ttl"
REPORT_FILE = DATA_QUALITY / "abox_generation_report.md"

# ── Brick → CIM class mapping ───────────────────────────────────────────────
BRICK_TO_CIM_CLASS = {
    "brk:Chiller":                    "Chiller",
    "brk:Cooling_Tower":              "CoolingTower",
    "brk:Boiler":                     "Boiler",
    "brk:Heat_Exchanger":             "HeatExchanger",
    "brk:Air_Handler_Unit":           "AHU",
    "brk:VAV_Box":                    "VAV_Terminal",
    "brk:Fan":                        "Fan",
    "brk:Supply_Fan":                 "SupplyFan",
    "brk:Exhaust_Fan":                "ExhaustFan",
    "brk:Diffuser":                   "SupplyAirDiffuser",
    "brk:Return_Air_Grille":          "ReturnAirGrille",
    "brk:Exhaust_Air_Grille":         "ExhaustAirGrille",
    "brk:Filter":                     "HEPA_Filter",
    "brk:Pump":                       "Pump",
    "brk:Coil":                       "Coil",
    "brk:Sensor":                     "Sensor",
    "brk:Actuator":                   "Actuator",
    "brk:Alarm_Panel":                "FireAlarmPanel",
    "brk:Electrical_System":          "Electrical_Equipment",
    "brk:Fire_Control_Panel":         "FireAlarmPanel",
    "brk:Energy_Conversion_Device":   "EnergyConversionDevice",
    "brk:Storage_Tank":               "WaterTank",
}

# ── CIM ID generation rules (three-segment: TYPE-LOCATION-SEQ) ──────────────
#    Returns (prefix, location_code)
BRICK_TO_ID_RULE: dict[str, tuple[str, str]] = {
    "brk:Diffuser":               ("DIFF", "SD"),
    "brk:Return_Air_Grille":      ("DIFF", "RR"),
    "brk:Exhaust_Air_Grille":     ("DIFF", "ER"),
    "brk:Fan":                    ("FAN",  "GN"),
    "brk:Supply_Fan":             ("FAN",  "SF"),
    "brk:Exhaust_Fan":            ("FAN",  "EF"),
    "brk:VAV_Box":                ("VAV",  "BOX"),
    "brk:Air_Handler_Unit":       ("AHU",  ""),
    "brk:Chiller":                ("CH",   ""),
    "brk:Cooling_Tower":          ("CT",   ""),
    "brk:Boiler":                 ("BLR",  ""),
    "brk:Heat_Exchanger":         ("HX",   ""),
    "brk:Filter":                 ("FLT",  ""),
    "brk:Pump":                   ("PMP",  ""),
    "brk:Coil":                   ("COIL", ""),
    "brk:Sensor":                 ("SEN",  ""),
    "brk:Actuator":               ("ACT",  ""),
    "brk:Alarm_Panel":            ("ALP",  ""),
    "brk:Electrical_System":      ("ELEC", ""),
    "brk:Fire_Control_Panel":     ("FCP",  ""),
    "brk:Energy_Conversion_Device": ("ECD", ""),
    "brk:Storage_Tank":           ("TK",   ""),
}

# ── Space type mapping: cim_type → CIM ontology class ───────────────────────
SPACE_TYPE_MAP = {
    "OR":         "OperatingRoom",
    "ICU":        "IntensiveCareUnit",
    "WARD":       "WardRoom",
    "EXAM":       "ExamRoom",
    "OFFICE":     "OfficeRoom",
    "WAITING":    "WaitingArea",
    "CORRIDOR":   "Corridor",
    "TOILET":     "ToiletRoom",
    "RECEPTION":  "ReceptionArea",
    "ADMIN":      "AdministrativeRoom",
    "MECHANICAL": "MechanicalRoom",
    "UNKNOWN":    "Room",
}

# ── Turtle prefix block ─────────────────────────────────────────────────────
TURTLE_PREFIXES = """\
# =============================================================================
# CIM ABox — NBU Medical Clinic Instance Data
# Generated by step6_ifc_to_cim_abox.py
#
# Source : IFC→Brick→CIM mapping (ifc_to_cim_mapping.json)
# Ontology: CIM v4.0 (ISO 19650 four-layer)
# Date   : {date}
# =============================================================================

@prefix rdf:       <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:      <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl:       <http://www.w3.org/2002/07/owl#> .
@prefix xsd:       <http://www.w3.org/2001/XMLSchema#> .

@prefix cim:       <https://cim.medical/ontology/v3.4#> .
@prefix cim-equip: <https://cim.medical/ontology/v3.4/equipment#> .
@prefix cim-space: <https://cim.medical/ontology/v3.4/space#> .
@prefix cim-ctrl:  <https://cim.medical/ontology/v3.4/control#> .
@prefix cim-flow:  <https://cim.medical/ontology/v3.4/flow#> .
@prefix cim-d:     <https://cim.medical/ontology/v4.0/design#> .
@prefix cim-c:     <https://cim.medical/ontology/v4.0/conceptual#> .
@prefix cim-op:    <https://cim.medical/ontology/v4.0/operational#> .

@prefix inst:      <https://cim.medical/instance/nbu_medical_clinic/> .
@prefix ifc:       <https://standards.buildingsmart.org/IFC/DEV/IFC4/ADD2_TC1/OWL#> .

"""


def sanitize_id(s: str) -> str:
    """Make a string safe for use as a Turtle local name."""
    return re.sub(r"[^A-Za-z0-9_-]", "_", s).strip("_")


def escape_turtle_string(s: str) -> str:
    """Escape characters that are special in Turtle string literals."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


# ── ID Counters ─────────────────────────────────────────────────────────────
_seq_counters: dict[str, int] = defaultdict(int)


def generate_equipment_id(brick_class: str) -> str:
    """Generate a three-segment CIM ID: TYPE-LOCATION-SEQ."""
    rule = BRICK_TO_ID_RULE.get(brick_class)
    if rule is None:
        # Fallback: use brick class suffix
        prefix = sanitize_id(brick_class.split(":")[-1][:4].upper())
        loc = ""
    else:
        prefix, loc = rule

    key = f"{prefix}-{loc}" if loc else prefix
    _seq_counters[key] += 1
    seq = _seq_counters[key]

    if loc:
        return f"{prefix}-{loc}-{seq:03d}"
    return f"{prefix}-{seq:03d}"


def generate_floor_id(ifc_name: str) -> str:
    """Generate a floor CIM ID from the IFC name."""
    clean = sanitize_id(ifc_name).replace(" ", "_")
    return f"FLOOR-{clean}"


def generate_room_id(ifc_name: str) -> str:
    """Generate a room CIM ID from the IFC name."""
    clean = sanitize_id(ifc_name)
    return f"ROOM-{clean}"


# ── Triple generators ───────────────────────────────────────────────────────

def equipment_triple(cim_id: str, cim_class: str, ifc_name: str,
                     ifc_tag: str, ifc_id: str, system_ref: str = "") -> str:
    """Generate Turtle block for an equipment instance."""
    label = escape_turtle_string(ifc_name)
    tag = escape_turtle_string(ifc_tag or cim_id)
    lines = [
        f'inst:{cim_id} a cim-equip:{cim_class} ;',
        f'    rdfs:label "{label}"@en ;',
        f'    cim-d:designTag "{tag}" ;',
        f'    cim:hasEquipmentID "{cim_id}" ;',
        f'    cim:ifcGlobalId "{escape_turtle_string(ifc_id)}" ;',
    ]
    if system_ref:
        lines.append(f'    cim:hasSystemReference "{escape_turtle_string(system_ref)}" ;')
    # Close the block
    lines[-1] = lines[-1].rstrip(" ;") + " ."
    return "\n".join(lines)


def floor_triple(cim_id: str, ifc_name: str, ifc_id: str) -> str:
    """Generate Turtle block for a floor instance."""
    label = escape_turtle_string(ifc_name)
    return (
        f'inst:{cim_id} a cim-space:Floor ;\n'
        f'    rdfs:label "{label}"@en ;\n'
        f'    cim:ifcGlobalId "{escape_turtle_string(ifc_id)}" .'
    )


def space_triple(cim_id: str, space_class: str, ifc_name: str,
                 ifc_id: str, floor_id: str | None = None) -> str:
    """Generate Turtle block for a space (room) instance."""
    label = escape_turtle_string(ifc_name)
    lines = [
        f'inst:{cim_id} a cim-space:{space_class} ;',
        f'    rdfs:label "{label}"@en ;',
        f'    cim:ifcGlobalId "{escape_turtle_string(ifc_id)}" ;',
    ]
    if floor_id:
        lines.append(f'    cim:isPartOf inst:{floor_id} ;')
    lines[-1] = lines[-1].rstrip(" ;") + " ."
    return "\n".join(lines)


# ── Main conversion logic ───────────────────────────────────────────────────

def convert(data: dict) -> tuple[str, dict]:
    """
    Convert all mapped instances to Turtle ABox triples.

    Returns (turtle_text, stats_dict).
    """
    blocks: list[str] = []
    stats: dict = {
        "equipment_by_class": Counter(),
        "spaces_by_type": Counter(),
        "floors": 0,
        "total_equipment": 0,
        "total_spaces": 0,
        "total_floors": 0,
        "skipped": 0,
        "sources": [],
    }

    # Collect all floor instances first (deduplicated by ifc_name)
    # so we can link rooms to floors
    floor_map: dict[str, str] = {}  # ifc_name → cim_id
    all_instances: list[dict] = []

    for section_key in ("hvac", "arch"):
        section = data.get(section_key, {})
        if section_key not in stats["sources"] and section.get("mapped_instances"):
            stats["sources"].append(section_key)

        for inst in section.get("mapped_instances", []):
            all_instances.append({**inst, "_source": section_key})

    # ── Pass 1: Collect floor instances ──────────────────────────────────
    for inst in all_instances:
        if inst["brick_class"] == "cim:Floor":
            name = inst["ifc_name"]
            if name not in floor_map:
                fid = generate_floor_id(name)
                floor_map[name] = fid

    # ── Pass 2: Generate floor triples ───────────────────────────────────
    blocks.append("# " + "=" * 75)
    blocks.append("# FLOORS")
    blocks.append("# " + "=" * 75)
    blocks.append("")

    seen_floors: set[str] = set()
    for inst in all_instances:
        if inst["brick_class"] == "cim:Floor":
            name = inst["ifc_name"]
            if name in seen_floors:
                continue
            seen_floors.add(name)
            fid = floor_map[name]
            blocks.append(floor_triple(fid, name, inst["ifc_id"]))
            blocks.append("")
            stats["total_floors"] += 1

    # ── Pass 3: Build space lookup from space_mappings ───────────────────
    # Map ifc_id → cim_type from space_mappings in both sections
    space_type_lookup: dict[str, str] = {}
    for section_key in ("hvac", "arch"):
        section = data.get(section_key, {})
        for sm in section.get("space_mappings", []):
            space_type_lookup[sm["ifc_id"]] = sm.get("cim_type", "UNKNOWN")

    # ── Pass 4: Generate space (Room) triples ────────────────────────────
    blocks.append("# " + "=" * 75)
    blocks.append("# SPACES (Rooms)")
    blocks.append("# " + "=" * 75)
    blocks.append("")

    seen_rooms: set[str] = set()
    for inst in all_instances:
        if inst["brick_class"] == "cim:Room":
            ifc_id = inst["ifc_id"]
            name = inst["ifc_name"]
            if ifc_id in seen_rooms:
                continue
            seen_rooms.add(ifc_id)

            room_id = generate_room_id(name)
            cim_type_key = space_type_lookup.get(ifc_id, "UNKNOWN")
            space_class = SPACE_TYPE_MAP.get(cim_type_key, "Room")

            # Try to infer floor from room name prefix (e.g. "2A03" → Second Floor)
            floor_id = _infer_floor(name, floor_map)

            blocks.append(space_triple(room_id, space_class, name, ifc_id, floor_id))
            blocks.append("")
            stats["total_spaces"] += 1
            stats["spaces_by_type"][space_class] += 1

    # ── Pass 5: Generate space triples from space_mappings not already
    #    covered by mapped_instances ──────────────────────────────────────
    for section_key in ("hvac", "arch"):
        section = data.get(section_key, {})
        for sm in section.get("space_mappings", []):
            ifc_id = sm["ifc_id"]
            if ifc_id in seen_rooms:
                continue
            seen_rooms.add(ifc_id)

            name = sm["ifc_name"]
            room_id = generate_room_id(name)
            cim_type_key = sm.get("cim_type", "UNKNOWN")
            space_class = SPACE_TYPE_MAP.get(cim_type_key, "Room")
            floor_id = _infer_floor(name, floor_map)

            blocks.append(space_triple(room_id, space_class, name, ifc_id, floor_id))
            blocks.append("")
            stats["total_spaces"] += 1
            stats["spaces_by_type"][space_class] += 1

    # ── Pass 6: Generate equipment triples ───────────────────────────────
    blocks.append("# " + "=" * 75)
    blocks.append("# EQUIPMENT")
    blocks.append("# " + "=" * 75)
    blocks.append("")

    seen_equip: set[str] = set()
    for inst in all_instances:
        bc = inst["brick_class"]
        if bc in ("cim:Floor", "cim:Room", "cim:Zone"):
            continue

        ifc_id = inst["ifc_id"]
        if ifc_id in seen_equip:
            continue
        seen_equip.add(ifc_id)

        cim_class = BRICK_TO_CIM_CLASS.get(bc)
        if cim_class is None:
            stats["skipped"] += 1
            continue

        cim_id = generate_equipment_id(bc)
        ifc_name = inst.get("ifc_name", "")
        ifc_tag = inst.get("ifc_tag", "")

        blocks.append(equipment_triple(cim_id, cim_class, ifc_name, ifc_tag, ifc_id))
        blocks.append("")
        stats["total_equipment"] += 1
        stats["equipment_by_class"][cim_class] += 1

    turtle = TURTLE_PREFIXES.format(date=datetime.now().strftime("%Y-%m-%d")) + "\n".join(blocks)
    return turtle, stats


def _infer_floor(room_name: str, floor_map: dict[str, str]) -> str | None:
    """
    Heuristic: infer floor from room name prefix.
    - Names starting with '1' or '1x' → First Floor
    - Names starting with '2' or '2x' → Second Floor
    - Names starting with '3' or '3x' → Third Floor / Roof
    - Names starting with 'S'         → Site level (TOF Footing)
    - Names starting with 'E'         → First Floor (ground equipment)
    """
    if not room_name:
        return None

    first = room_name[0].upper()
    if first == "1":
        for fname in ("First Floor",):
            if fname in floor_map:
                return floor_map[fname]
    elif first == "2":
        for fname in ("Second Floor",):
            if fname in floor_map:
                return floor_map[fname]
    elif first == "3":
        for fname in ("Roof - Main", "Roof - Mech"):
            if fname in floor_map:
                return floor_map[fname]
    elif first == "S":
        for fname in ("TOF Footing",):
            if fname in floor_map:
                return floor_map[fname]
    return None


def run_shacl_validation(ttl_path: Path) -> str | None:
    """
    Optionally validate generated ABox against CIM SHACL constraints.
    Returns validation result text or None.
    """
    try:
        from pyshacl import validate as shacl_validate
    except ImportError:
        print("  [INFO] pyshacl not installed, skipping SHACL validation")
        return None

    try:
        import rdflib
    except ImportError:
        print("  [INFO] rdflib not installed, skipping SHACL validation")
        return None

    print("  [INFO] Running SHACL validation...")

    # Load ABox
    data_graph = rdflib.Graph()
    data_graph.parse(str(ttl_path), format="turtle")

    # Try to load TBox ontology files
    onto_graph = rdflib.Graph()
    ontology_files = list(CIM_ONTOLOGY.glob("*.ttl"))
    for f in ontology_files:
        try:
            onto_graph.parse(str(f), format="turtle")
        except Exception:
            pass  # Skip files that fail to parse

    # Try to load SHACL constraints
    shacl_file = CIM_ONTOLOGY.parent.parent / "rules" / "shacl_constraints.ttl"
    shacl_graph = None
    if shacl_file.exists():
        shacl_graph = rdflib.Graph()
        try:
            shacl_graph.parse(str(shacl_file), format="turtle")
        except Exception:
            shacl_graph = None

    if shacl_graph is None:
        print("  [INFO] No SHACL shapes found, skipping validation")
        return None

    # Merge TBox into data graph for validation context
    for triple in onto_graph:
        data_graph.add(triple)

    try:
        conforms, results_graph, results_text = shacl_validate(
            data_graph,
            shacl_graph=shacl_graph,
            inference="none",
            abort_on_first=False,
        )
        status = "PASS" if conforms else "FAIL"
        print(f"  [SHACL] Validation result: {status}")
        return f"**SHACL Validation**: {status}\n\n```\n{results_text[:3000]}\n```"
    except Exception as e:
        msg = f"SHACL validation error: {e}"
        print(f"  [WARN] {msg}")
        return f"**SHACL Validation**: ERROR — {msg}"


def generate_report(stats: dict, ttl_path: Path, shacl_result: str | None) -> str:
    """Generate the ABox generation report in Markdown."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    total = stats["total_equipment"] + stats["total_spaces"] + stats["total_floors"]

    lines = [
        "# ABox Generation Report — NBU Medical Clinic",
        "",
        f"**Generated**: {now}",
        f"**Source**: `validation/ifc_to_cim_mapping.json`",
        f"**Output**: `{ttl_path.relative_to(ROOT)}`",
        f"**IFC Sections processed**: {', '.join(stats['sources'])}",
        "",
        "## Summary",
        "",
        f"| Metric | Count |",
        f"|--------|-------|",
        f"| Total CIM instances | {total} |",
        f"| Equipment instances | {stats['total_equipment']} |",
        f"| Space instances | {stats['total_spaces']} |",
        f"| Floor instances | {stats['total_floors']} |",
        f"| Skipped (no CIM mapping) | {stats['skipped']} |",
        "",
        "## Equipment Breakdown by CIM Class",
        "",
        "| CIM Class | Count |",
        "|-----------|-------|",
    ]
    for cls, cnt in stats["equipment_by_class"].most_common():
        lines.append(f"| {cls} | {cnt} |")

    lines += [
        "",
        "## Space Breakdown by CIM Type",
        "",
        "| Space Class | Count |",
        "|-------------|-------|",
    ]
    for cls, cnt in stats["spaces_by_type"].most_common():
        lines.append(f"| {cls} | {cnt} |")

    lines += [
        "",
        "## CIM ID Generation Rules",
        "",
        "| Brick Class | ID Pattern | Example |",
        "|-------------|-----------|---------|",
        "| brk:Diffuser | DIFF-SD-{seq:03d} | DIFF-SD-001 |",
        "| brk:Return_Air_Grille | DIFF-RR-{seq:03d} | DIFF-RR-001 |",
        "| brk:Exhaust_Air_Grille | DIFF-ER-{seq:03d} | DIFF-ER-001 |",
        "| brk:Fan | FAN-GN-{seq:03d} | FAN-GN-001 |",
        "| brk:Supply_Fan | FAN-SF-{seq:03d} | FAN-SF-001 |",
        "| brk:Exhaust_Fan | FAN-EF-{seq:03d} | FAN-EF-001 |",
        "| brk:VAV_Box | VAV-BOX-{seq:03d} | VAV-BOX-001 |",
        "| brk:Air_Handler_Unit | AHU-{seq:03d} | AHU-001 |",
        "| brk:Chiller | CH-{seq:03d} | CH-001 |",
        "| cim:Floor | FLOOR-{name} | FLOOR-First_Floor |",
        "| cim:Room | ROOM-{name} | ROOM-2A03 |",
        "",
    ]

    if shacl_result:
        lines += [
            "## SHACL Validation",
            "",
            shacl_result,
            "",
        ]

    lines += [
        "## Notes",
        "",
        "- Instances are deduplicated by IFC GlobalId across HVAC and Arch sections",
        "- Room-to-floor linkage uses heuristic based on room name prefix",
        "- Space type classification uses `cim_type` from `space_mappings`",
        "- UNKNOWN spaces default to `cim-space:Room`",
        "",
    ]

    return "\n".join(lines)


# ── Entry point ──────────────────────────────────────────────────────────────

def main():
    print("=" * 70)
    print("  Step 6 — IFC → CIM ABox Batch Instance Conversion")
    print("=" * 70)

    # 1. Load mapping data
    if not MAPPING_FILE.exists():
        print(f"[ERROR] Mapping file not found: {MAPPING_FILE}")
        print("        Run step2_ifc_to_brick_mapping.py first.")
        sys.exit(1)

    print(f"\n[1/5] Loading {MAPPING_FILE.name} ...")
    with open(MAPPING_FILE) as f:
        data = json.load(f)

    hvac_count = len(data.get("hvac", {}).get("mapped_instances", []))
    arch_count = len(data.get("arch", {}).get("mapped_instances", []))
    hvac_spaces = len(data.get("hvac", {}).get("space_mappings", []))
    arch_spaces = len(data.get("arch", {}).get("space_mappings", []))
    print(f"  HVAC mapped instances: {hvac_count}")
    print(f"  Arch mapped instances: {arch_count}")
    print(f"  HVAC space_mappings : {hvac_spaces}")
    print(f"  Arch space_mappings : {arch_spaces}")

    # 2. Convert to Turtle
    print(f"\n[2/5] Generating CIM v4.0 Turtle ABox triples ...")
    turtle_text, stats = convert(data)

    # 3. Write output
    ABOX_DIR.mkdir(parents=True, exist_ok=True)
    print(f"\n[3/5] Writing Turtle to {OUTPUT_TTL.relative_to(ROOT)} ...")
    OUTPUT_TTL.write_text(turtle_text, encoding="utf-8")
    print(f"  File size: {OUTPUT_TTL.stat().st_size:,} bytes")

    # 4. Print summary
    total = stats["total_equipment"] + stats["total_spaces"] + stats["total_floors"]
    print(f"\n[4/5] Conversion Summary")
    print(f"  {'─' * 50}")
    print(f"  Total CIM instances generated : {total}")
    print(f"    Equipment                   : {stats['total_equipment']}")
    print(f"    Spaces (rooms)              : {stats['total_spaces']}")
    print(f"    Floors                      : {stats['total_floors']}")
    print(f"    Skipped (no CIM mapping)    : {stats['skipped']}")
    print(f"  {'─' * 50}")
    print(f"\n  Equipment by CIM class:")
    for cls, cnt in stats["equipment_by_class"].most_common():
        print(f"    {cls:<30} {cnt:>5}")
    print(f"\n  Spaces by CIM type:")
    for cls, cnt in stats["spaces_by_type"].most_common():
        print(f"    {cls:<30} {cnt:>5}")

    # 5. SHACL validation (optional)
    print(f"\n[5/5] SHACL Validation ...")
    shacl_result = run_shacl_validation(OUTPUT_TTL)

    # 6. Generate report
    DATA_QUALITY.mkdir(parents=True, exist_ok=True)
    report = generate_report(stats, OUTPUT_TTL, shacl_result)
    REPORT_FILE.write_text(report, encoding="utf-8")
    print(f"\n  Report written to: {REPORT_FILE.relative_to(ROOT)}")

    print(f"\n{'=' * 70}")
    print(f"  DONE — {total} CIM instances generated")
    print(f"{'=' * 70}")


if __name__ == "__main__":
    main()
